version: '3.8'

services:
  web:
    build: .
    container_name: lamp-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - lamp-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: lamp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

volumes:
  db_data:

networks:
  lamp-network: